---
- name: 'git: netdiscover'
  git:
    repo: https://github.com/jdiazbb/netdiscover
    dest: /opt/netdiscover
    update: yes

- name: 'install: netdiscover'
  shell: bash update-oui-database.sh && cmake . && make && make install
  args:
    chdir: /opt/netdiscover
