---
- name: 'git: netdiscover'
  git:
    repo: https://github.com/jdiazbb/netdiscover
    dest: /opt/netdiscover
    update: yes
    force: yes

- name: 'xbps: install netdiscover dependencies'
  xbps: name=libpcap-devel,libnet-devel state=present

- name: 'install source: netdiscover'
  shell: bash update-oui-database.sh && cmake . && make && make install
  args:
    chdir: /opt/netdiscover
