---
- name: 'git: xsser'
  git: 
    repo: https://github.com/epsylon/xsser.git
    dest: /opt/xsser

- name: 'xsser: install dependencies'
  pip: 
    name: pycurl,bs4,geoip2,gobject,cairocffi


- name: 'xsser: symlink executable'
  file:
      src: /opt/xsser/xsser
      dest: /usr/bin/xsser
      owner: root
      group: root
      mode: 0755 
      state: link
      force: yes


#     link: shell: ln -s /opt/xsser/xsser /usr/bin/xsser
