---
- block:
  - name: 'golang: download archive'
    get_url: 
      url: https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz
      dest: /tmp/golang.tar.gz
      checksum: sha256:0567734d558aef19112f2b2873caa0c600f1b4a5827930eb5a7f35235219e9d8

  - name: 'golang: extract archive'
    unarchive:
      dest: /usr/local
      remote_src: yes 
      src: /tmp/golang.tar.gz

  - name: 'golang : add golang directory to $PATH'
    lineinfile:
      insertafter: EOF
      line: export PATH=$PATH:/usr/local/go/bin
      path: '{{ item }}'
      state: present
    with_items:
      - /etc/profile

  - name: 'golang : setup $GOPATH'
    lineinfile:
      insertafter: EOF
      line: export GOPATH=/root/.go
      path: '{{ item }}'
      state: present
    with_items:
      - /etc/profile

  - name: 'golang : setup $GOBIN'
    lineinfile:
      insertafter: EOF
      line: export GOBIN=$GOPATH/bin
      path: '{{ item }}'
      state: present
    with_items:
      - /etc/profile

  - name: 'golang : cleanup fragments'
    file:
      dest: /tmp/golang.tar.gz
      state: absent
